import type { Metadata } from "next";
// Dans la nouvelle version de Next.js, Geist est maintenant disponible directement !
import { Inter, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

// Configuration des polices Google natives de la nouvelle version
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter", // Optionnel : pour l'isoler si besoin
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="fr" 
      className={cn("dark", geistSans.variable, geistMono.variable)}
      style={{ colorScheme: "dark" }}
    >
      <body className="bg-background text-foreground antialiased font-sans">
        {children}
      </body>
    </html>
  );
}
